# Generated by Django 6.0.5 on 2026-07-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('telebirr', 'Telebirr'), ('cbe', 'CBE'), ('boa', 'BOA'), ('awash', 'Awash'), ('other', 'Other')], help_text='Payment method used (CBE, Telebirr, etc.)', max_length=20, null=True),
        ),
    ]
